# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'SwfitTestProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwfitTestProj
  pod 'RxSwift'

  target 'SwfitTestProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwfitTestProjUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
